# Read the documentation: https://fosrestbundle.readthedocs.io/en/3.x/
fos_rest:
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors
    view:
        view_response_listener: true
        formats: { json: true }
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: 'json' }
    exception:
        enabled: true